OLED_ENABLE = yes
OLED_DRIVER = ssd1306      # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGB_MATRIX_ENABLE = no     # Disable keyboard RGB matrix, as it is enabled by default on rev3
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
CONVERT_TO = promicro_rp2040
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
LTO_ENABLE = no            # Workaround for https://github.com/qmk/qmk_firmware/issues/24725
